### ISSUE TITLE
NATS server debug logs are not verbose

### ISSUE THREAD

**Issue by imranrazakhan** [nats-io/nats-server#2587]
I have deployed NATS-2.6.1 with MQTT and i observed that debug logs are not verbose

Like I enabled debug logs to identify which client is continuously opening and closing connection

```
[114] 2021/09/30 10:30:41.386108 [DBG] 10.244.0.1:53288 - mid:37739 - Client connection closed: Client Closed
[114] 2021/09/30 10:30:41.838201 [DBG] 10.244.0.1:49586 - mid:37740 - Client connection created
[114] 2021/09/30 10:30:41.959710 [DBG] 10.244.0.1:49586 - mid:37740 - Client connection closed: Client Closed
[114] 2021/09/30 10:30:51.255027 [DBG] 10.244.0.1:53798 - mid:37741 - Client connection created
[114] 2021/09/30 10:30:51.401562 [DBG] 10.244.0.1:53798 - mid:37741 - Client connection closed: Client Closed
[114] 2021/09/30 10:30:51.847412 [DBG] 10.244.0.1:49702 - mid:37742 - Client connection created
[114] 2021/09/30 10:30:51.981592 [DBG] 10.244.0.1:49702 - mid:37742 - Client connection closed: Client Closed
[114] 2021/09/30 10:31:01.251372 [DBG] 10.244.0.1:54290 - mid:37743 - Client connection created
```

Above logs are not giving any hint, its good to have clientid in debug logs, enabling trace would not be good idea :(

Another example, I restarted MQTT clients and start getting below error and client were not able to connect, No hint so i restarted NATS and it fixed issue :( 

```
[7] 2021/09/29 13:38:31.210414 [ERR] 10.244.0.1:58548 - mid:24322 - wrong last sequence: 0 (10071)
[7] 2021/09/29 13:38:31.242765 [ERR] 10.244.0.1:52434 - mid:24324 - wrong last sequence: 0 (10071)
[7] 2021/09/29 13:38:31.246050 [ERR] 10.244.0.1:52436 - mid:24325 - wrong last sequence: 0 (10071)
[7] 2021/09/29 13:38:31.249087 [ERR] 10.244.0.1:52438 - mid:24326 - wrong last sequence: 0 (10071)
[7] 2021/09/29 13:38:31.253428 [ERR] 10.244.0.1:52440 - mid:24327 - wrong last sequence: 0 (10071)
[7] 2021/09/29 13:38:31.288618 [ERR] 10.244.0.1:52138 - mid:24328 - wrong last sequence: 0 (10071)
[7] 2021/09/29 13:38:31.310963 [ERR] 10.244.0.1:52040 - mid:24329 - wrong last sequence: 0 (10071)
```

It would be nice if we have more detail description for errors.

**Comment by derekcollison** [comment]
Try `nats-server -DVV`

**Comment by kozlovic** [comment]
@imranrazakhan Remember that we have introduced system events that contain mqtt client ID (you were one to request this feature). So say that you have a `system_account` defined, then you can run a subscription on `$SYS.ACCOUNT.<mqtt account name>.CONNECT` to get details about the connected client. Here is an example of the output:
```
{"type":"io.nats.server.advisory.v1.client_connect","id":"rAHxNYaPT47P6M0FgEeqln","timestamp":"2021-09-30T15:21:57.249393Z","server":{"name":"mqtt_server","host":"0.0.0.0","id":"NASVUXNELTL4OGIVIXBEVNZ3RATF75BTPFHMPQLEQJTHFKIAFXXASND5","ver":"2.6.2-beta","seq":133,"jetstream":true,"time":"2021-09-30T15:21:57.24942Z"},"client":{"start":"2021-09-30T15:21:57.249318Z","host":"::1","id":30,"acc":"MQTT","user":"mqtt","jwt":"pwd","kind":"Client","client_type":"mqtt","client_id":"client_0"}}
```
As you can see the CONNECT event has a field called "client_id" (should have been mqtt_client_id but we forgot to change this before the release...). In this case my client is named `client_0`.

That being said, we could consider logging the mqtt connect trace (such as below) as a debug statement:
```
3522] 2021/09/30 09:25:43.007640 [TRC] [::1]:49908 - mid:16 - <<- [CONNECT clientID=client_0 keepAlive=45s username=mqtt password=****]
```

> Another example, I restarted MQTT clients and start getting below error and client were not able to connect, No hint so i restarted NATS and it fixed issue :(

Would need more information on how to reproduce. Where you running the NATS server(s) in cluster mode or standalone? Are the MQTT clients setting the "clean session" flag or not? Do they create subscriptions?
When they restarted and you got this error, you said that you cleared the error by "restarting NATS", you mean the server(s)? (if clustered, the whole cluster? with or without the state?).

**Comment by imranrazakhan** [comment]
@kozlovic Thanks for your reply, 

```
3522] 2021/09/30 09:25:43.007640 [TRC] [::1]:49908 - mid:16 - <<- [CONNECT clientID=client_0 keepAlive=45s username=mqtt password=****]
```
It would be nice to have this output as debug, But I would also like to have clientid in close connection logs.

For other issue:

`[7] 2021/09/29 13:38:31.210414 [ERR] 10.244.0.1:58548 - mid:24322 - wrong last sequence: 0 (10071)`

> Where you running the NATS server(s) in cluster mode or standalone?

I am running standalone NATS server in kubernetes environment.

> Are the MQTT clients setting the "clean session" flag or not? Do they create subscriptions?

Yes they create subscription too.

> When they restarted and you got this error, you said that you cleared the error by "restarting NATS", you mean the server(s)?

NATS server

**Comment by kozlovic** [comment]
> Another example, I restarted MQTT clients and start getting below error and client were not able to connect, No hint so i restarted NATS and it fixed issue :(
```
[7] 2021/09/29 13:38:31.210414 [ERR] 10.244.0.1:58548 - mid:24322 - wrong last sequence: 0 (10071)
```
I can tell that this is NOT from a v2.6.1. The error message would have been different, something like:
```
[ERR] [::1]:58356 - mid:8012 - unable to persist session "client_0" (seq=12003): wrong last sequence: 0 (10071)
```
I have added to the error message in later releases, so it seems to be that you are running v2.5.0 or earlier.
This specific issue was due to a defect in the filestore compaction code, which has been addressed in v2.6.0 (https://github.com/nats-io/nats-server/pull/2522).

**Comment by kozlovic** [comment]
Regarding connection debug statements, unfortunately I can't change the:
```
mid:37740 - Client connection created
```
At this point in time, the client has not sent the CONNECT protocol, so there would be no client id to display. This debug statement is printed "as soon" as a TCP connection has been accepted. The connection can fail past that point, say because of TLS, auth, etc..
I *could* add a debug statement to the effect:
```
[19229] 2021/09/30 16:17:31.171011 [DBG] [::1]:54399 - mid:811 - Client ID "client_1" connected
```
So in the log there would be (not necessarily one right after this other since other debug/trace statements can go in between):
```
[19229] 2021/09/30 16:17:31.170825 [DBG] [::1]:54399 - mid:811 - Client connection created
[19229] 2021/09/30 16:17:31.171011 [DBG] [::1]:54399 - mid:811 - Client ID "client_1" connected
```
For the close connection debug statement, then it is different, I could "enhance" the current one since then in that case we possibly have the client ID:
```
[19229] 2021/09/30 16:17:31.573328 [DBG] [::1]:54399 - mid:811 - Client ID "client_1" connection closed: Client Closed
```
But wonder if then I should not have dedicated ones so that we don't "break" applications that inspect logs and look for "Client connection closed:".
We could have:
```
[19229] 2021/09/30 16:17:31.573328 [DBG] [::1]:54399 - mid:811 - Client ID "client_1" disconnected
[19229] 2021/09/30 16:17:31.573328 [DBG] [::1]:54399 - mid:811 - Client connection closed: Client Closed
```
That being said, this is a bit redundant since with the client id connected event and mid number, you can correlate the two events (with the mid). But I understand it may be easier to not have to correlate.

But again, with system events, you have all this info.

**Comment by imranrazakhan** [comment]
@kozlovic Thanks you very much for detail reply.

> I can tell that this is NOT from a v2.6.1. The error message would have been different, something like:

Yes you are right this was from 2.5.0, Sorry i missed as it was from other testing server.

> But I understand it may be easier to not have to correlate.

Your suggested debug will help a lot, idea to have verbose logs is that support/operation team can understand problem without expert assistance or when they explaining problem to second level support at lease it has some valuable information.

**Comment by imranrazakhan** [comment]
@kozlovic Couple of more logs which needs changes

It would be nice to have clientid in this logline
`2021/10/05 07:28:57.668884 [INF] 10.244.0.1:3203 - mid:129825 - Slow Consumer Detected: WriteDeadline of 5s exceeded with 1 chunks of 254 total bytes.`

No hint for below log
`[114] 2021/10/05 04:06:39.294267 [WRN] 10.244.0.1:34480 - mid:128400 - Readloop processing time: 2.575147058s`

**Comment by imranrazakhan** [comment]
@kozlovic Thanks for providing fix for logs, I think you missed to comment on following logs, It would be nice to have clientid in below log too

`2021/10/05 07:28:57.668884 [INF] 10.244.0.1:3203 - mid:129825 - Slow Consumer Detected: WriteDeadline of 5s exceeded with 1 chunks of 254 total bytes.`
