### ISSUE TITLE
Nats server pod gets stuck in KV stream catchup after restart

### ISSUE THREAD

**Issue by andersroos** [nats-io/nats-server#5205]
### Observed behavior

I discovered this when exploring key value and testing resillience and performace among other things.

I used a helm install in kubernetes.

While updating a key value bucket (in memory, with replication 3) with about 1000 updates/s I restarted one pod. It never came back up and it got stuck in a stream catchup state (waited over 20 minutes). Subsequent restarts did not resolve the issue. It only got resolved after the stream was deleted (or in subsequent tests when all nats pods where stopped).

See also this thread in slack: https://natsio.slack.com/archives/C06EN6HCWE4/p1710151450266159

Stream:
```
Information for Stream KV_gamesession-state created 2024-03-06 16:42:33

              Subjects: $KV.gamesession-state.>
              Replicas: 3
               Storage: Memory

Options:

             Retention: Limits
       Acknowledgments: true
        Discard Policy: Old
      Duplicate Window: 2m0s
            Direct Get: true
     Allows Msg Delete: false
          Allows Purge: true
        Allows Rollups: true

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: 1
         Maximum Bytes: unlimited
           Maximum Age: 30m0s
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

Cluster Information:

                  Name: nats
                Leader: nats-0
               Replica: nats-1, current, seen 97ms ago
               Replica: nats-2, current, seen 97ms ago

State:

              Messages: 10
                 Bytes: 1.7 KiB
        First Sequence: 1,245,135 @ 2024-03-11 11:10:15 UTC
         Last Sequence: 1,245,155 @ 2024-03-11 11:10:15 UTC
      Deleted Messages: 11
      Active Consumers: 0
    Number of Subjects: 10
```

Log snippet:
```
[57] 2024/03/11 10:08:28.171728 [WRN] Catchup for stream '$G > KV_gamesession-state' stalled
[57] 2024/03/11 10:08:36.806848 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:08:46.806154 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:08:56.805914 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:08:58.172655 [WRN] Catchup for stream '$G > KV_gamesession-state' stalled
[57] 2024/03/11 10:08:58.177889 [WRN] Error applying entries to '$G > KV_gamesession-state': first sequence mismatch
[57] 2024/03/11 10:08:58.178309 [WRN] Resetting stream cluster state for '$G > KV_gamesession-state'
[57] 2024/03/11 10:08:58.301144 [WRN] Catchup for stream '$G > KV_gamesession-state' resetting first sequence: 1228966 on catchup request
[57] 2024/03/11 10:09:06.806746 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:09:16.805821 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:09:26.806109 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:09:28.301893 [WRN] Catchup for stream '$G > KV_gamesession-state' stalled
[57] 2024/03/11 10:09:36.806382 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:09:46.806260 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:09:56.806782 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:09:58.302241 [WRN] Catchup for stream '$G > KV_gamesession-state' stalled
[57] 2024/03/11 10:09:58.311134 [WRN] Error applying entries to '$G > KV_gamesession-state': first sequence mismatch
[57] 2024/03/11 10:09:58.311752 [WRN] Resetting stream cluster state for '$G > KV_gamesession-state'
[57] 2024/03/11 10:09:58.650302 [WRN] Catchup for stream '$G > KV_gamesession-state' resetting first sequence: 1243279 on catchup request
[57] 2024/03/11 10:10:06.806367 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:10:16.806423 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:10:26.805642 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:10:28.652230 [WRN] Catchup for stream '$G > KV_gamesession-state' stalled
[57] 2024/03/11 10:10:36.806734 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:10:46.805759 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:10:56.806693 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:10:58.652829 [WRN] Catchup for stream '$G > KV_gamesession-state' stalled
[57] 2024/03/11 10:10:58.656426 [WRN] Error applying entries to '$G > KV_gamesession-state': first sequence mismatch
[57] 2024/03/11 10:10:58.656974 [WRN] Resetting stream cluster state for '$G > KV_gamesession-state'
[57] 2024/03/11 10:10:58.988587 [WRN] Catchup for stream '$G > KV_gamesession-state' resetting first sequence: 1243279 on catchup request
[57] 2024/03/11 10:11:06.806418 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:11:16.805928 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:11:26.806630 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:11:28.989443 [WRN] Catchup for stream '$G > KV_gamesession-state' stalled
[57] 2024/03/11 10:11:36.806795 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:11:46.806430 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
[57] 2024/03/11 10:11:56.806165 [WRN] Healthcheck failed: "JetStream stream '$G > KV_gamesession-state' is not current"
```

### Expected behavior

I expected the restarted pod to catch up and come back into the cluster.

### Server and client version

Server version: 2.10.11
Client version (golang client): v1.32.0

### Host environment

Both server and client was running in managed Kubernetes in Google Cloud, using Google Filestore as perstistence layer.

### Steps to reproduce

It is a bit hard to reproduce, I only manged to reproduce it about 1/5 tries.

What I did was:
- Run a pod with a nats client that does updates in a keyvalue as fast as possibile. This is done with 100 goroutines in paralell. The goroutines will update a set of 10 keys (so 10 goroutines for each key).
- Seems to be running for a whle (I never reproduced when running it shorter than 5 minutes).
- Restart one pod, observe it not coming up (fail ready check) and see log like snippet above.

I also tried to reproduce using a file store for the stream, but didn't manage to do it within 10 tries or so.

**Comment by Tarasovych** [comment]
Same issue, nats-2.10.12. I went from 1 replica to 2 replicas for my stream, it helped.

**Comment by jzhn** [comment]
We have experienced the same issue in multiple environments for interest based Jetstream (not KV).

### Environment information
- Kubernetes based StatefulSet deployment with 3-replicas
- 3-replica, Interest based, file storage stream with single consumer
  - the file storage is persistent, backed by EBS backed PersistentVolume.
- Nats Helm chart: `1.1.10`
- Nats server: reproduciable on both `2.10.11` and `2.10.12`.
- The rolling deployment is graceful, as the helm chart ensures out of the box.

### Symptom
We noticed that the symptom seems to be caused by the `first_seq` of stream(s) go out of sync between replicas during deployment. One or two of the pods would have `first_seq` stuck, while other(s) would have `first_seq` growing up as messages are consumed. After the cluster went in this inconsistent state, the next rolling deployment would risk trigging the issue of `Error applying entries to X: first sequence mismatch` as mentioned in this issue.

![image](https://github.com/nats-io/nats-server/assets/4455171/a04ad7a4-74a3-47aa-a23a-acb23bab6dc8)
As demonstrated above, `first_seq` of a stream went out of sync, that `kubernetes-nats-1` and `kubernetes-nats-2` have their `first_seq` stuck, while `kubernetes-nats-0` has `first_seq` moving normally after a rolling restart.

### Reproduce
It's relatively easy to reproduce this issue in a 3-replica Kubernetes hosted NATs cluster with Jetstream enabled.

- Create an Interest based Stream with 3 replicas and file storage
- Create a consumer to above stream with subscribers that simply acks the message (to simulate a fast-moving consumer that always catches up with the publisher thus moving the first_seq of the interest-based stream).
- In a shell session, execute `nats pub <subject> --count 1000000000 "test message {{Count}} @ {{Time}}"` to keep publishing messages to the stream.
- In another shell session, execute `kubectl rollout restart statefulset/kubernetes-nats` to trigger graceful rolling restart of NATs cluster.

#### Actual behaviour

The `nats_stream_first_seq` metric of the stream went out of sync after the rolling deployment between 3 NATs nodes.

#### Expected behaviour

The `nats_stream_first_seq` metric of the stream should be consistent between all 3 NATs nodes.

### Mitigation

As @bondar-pavel suggested, editing the stream replicas to 1 and then back to 3 seems to be the only mitigation without losing data or causing downtime.

**Comment by derekcollison** [comment]
We have some improvements coming in 2.10.14 around this which hopefully can help.

If you are feeling adventuresome feel free to grab a binary from the `wq-orphan-msgs` branch as follows and see if the issue still presents.

`curl -sf https://binaries.nats.dev/github.com/nats-io/nats-server/v2@wq-orphan-msgs | sh`

**Comment by derekcollison** [comment]
We will start cleaning up and cherry picking into main and then into 2.10.14. Thanks for checking though!

**Comment by jnmoyne** [comment]
Note that 2.10.14 has now been released

**Comment by jzhn** [comment]
(copying the reply from nats slack)

I just repeated my chaos tests with 2.10.14, basically having a fast moving stream with a publisher (nats pub ) and an interest based consumer, while rolling restarting my 3-replica statefulset of NATs. Overall it’s been a LOT better. previously, almost 100% of the time the first_seq number of the fast moving stream would go out of sync, particularly the nats-2 instance that were restarted the first would almost always have its `first_seq` number stuck flat after restart. But now out of 8 restarts, I haven’t seen a single case.

Note that the first rolling restart did reproduce the `Healthcheck failed: "JetStream stream '$G > <stream-name>' is not current"` issue on one of the node, I had to stop the producer and purge the stream in order to get the health check passing. I wasn’t able to reproduce the same issue later on. I hope this is just a transient issue caused by the inherited bad state from 2.10.12.

Overall I’m really happy with 2.10.14. If it goes well it would address a major operation pain point of Jetstream. I’ll deploy it to prod soon and let you know if anything comes up. Thanks again for the hard work!

**Comment by bfoxstudio** [comment]
After restart 1 by 1 node in cluster on 2.10.14 we lost 60% kv storage
![image](https://github.com/nats-io/nats-server/assets/11800002/44468c9a-b856-413d-ab4c-1318e390c64e)

**Comment by derekcollison** [comment]
What does stream info for the underlying KV show?

**Comment by bfoxstudio** [comment]
# 01 node
```
~ # nats stream info KV_wh-px-egeo-e-shard1-kv
Information for Stream KV_wh-px-egeo-e-shard1-kv created 2024-05-08 14:38:06

              Subjects: $KV.wh-px-egeo-e-shard1-kv.>
              Replicas: 5
               Storage: File

Options:

             Retention: Limits
       Acknowledgments: true
        Discard Policy: New
      Duplicate Window: 2m0s
     Allows Msg Delete: false
          Allows Purge: true
        Allows Rollups: true

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: 1
         Maximum Bytes: unlimited
           Maximum Age: unlimited
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

Cluster Information:

                  Name: js_egeo_kv_shard1_infile
                Leader: js_egeo_kv_shard1_infile_node02
               Replica: js_egeo_kv_shard1_infile_node01, current, seen 686ms ago
               Replica: js_egeo_kv_shard1_infile_node03, current, seen 685ms ago
               Replica: js_egeo_kv_shard1_infile_node04, current, seen 685ms ago
               Replica: js_egeo_kv_shard1_infile_node05, current, seen 685ms ago

State:

              Messages: 64,660
                 Bytes: 19 MiB
        First Sequence: 806 @ 2024-05-08 14:54:04 UTC
         Last Sequence: 157,636 @ 2024-05-09 20:32:22 UTC
      Deleted Messages: 92,171
      Active Consumers: 1
    Number of Subjects: 64,660
    ```
  # 02 node
  ```
  ~ # nats stream info KV_wh-px-egeo-e-shard1-kv
Information for Stream KV_wh-px-egeo-e-shard1-kv created 2024-05-08 14:38:06

              Subjects: $KV.wh-px-egeo-e-shard1-kv.>
              Replicas: 5
               Storage: File

Options:

             Retention: Limits
       Acknowledgments: true
        Discard Policy: New
      Duplicate Window: 2m0s
     Allows Msg Delete: false
          Allows Purge: true
        Allows Rollups: true

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: 1
         Maximum Bytes: unlimited
           Maximum Age: unlimited
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

Cluster Information:

                  Name: js_egeo_kv_shard1_infile
                Leader: js_egeo_kv_shard1_infile_node02
               Replica: js_egeo_kv_shard1_infile_node01, current, seen 269ms ago
               Replica: js_egeo_kv_shard1_infile_node03, current, seen 268ms ago
               Replica: js_egeo_kv_shard1_infile_node04, current, seen 268ms ago
               Replica: js_egeo_kv_shard1_infile_node05, current, seen 268ms ago

State:

              Messages: 64,660
                 Bytes: 19 MiB
        First Sequence: 806 @ 2024-05-08 14:54:04 UTC
         Last Sequence: 157,648 @ 2024-05-09 20:33:42 UTC
      Deleted Messages: 92,183
      Active Consumers: 1
    Number of Subjects: 64,660
    ```
  
![image](https://github.com/nats-io/nats-server/assets/11800002/6624f404-24a6-4816-9c22-0b17997406ff)

**Comment by bfoxstudio** [comment]
> What does stream info for the underlying KV show?
and you can look on last 10k lines  log
[t0lbztwfu30jthnczav7o3nne_logs.txt](https://github.com/nats-io/nats-server/files/15267457/t0lbztwfu30jthnczav7o3nne_logs.txt)

**Comment by derekcollison** [comment]
We fixed an issue with discard new that is in main and will be in 2.10.15, however your KV may have already had inconsistencies so when a new leader was elected it used its state.

The way to sync a known good state is make sure that replica is leader, and scale down to 1 then back up. Once upgraded to 2.10.15 the issue should not occur anymore.

**Comment by bfoxstudio** [comment]
Version: 2.11.0-dev
                  Git Commit: 31b155b
                  Go Version: go1.21.9
                  
                  
![image](https://github.com/nats-io/nats-server/assets/11800002/58fccb29-5e4f-467f-9d2a-c63ca1d24656)


> We fixed an issue with discard new that is in main and will be in 2.10.15, however your KV may have already had inconsistencies so when a new leader was elected it used its state.
> 
> The way to sync a known good state is make sure that replica is leader, and scale down to 1 then back up. Once upgraded to 2.10.15 the issue should not occur anymore.

**Comment by bfoxstudio** [comment]
Try to terminate the server unsafe. i think problem near Sync Interval in file storage. if we kill meta leader we have problem on consumers - no new messages on subscribe. 
![image](https://github.com/nats-io/nats-server/assets/11800002/81c3e5c7-4c94-4242-8a3f-d713c2885628)

**Comment by derekcollison** [comment]
Could you retest from top of main branch or nightly builds?

**Comment by bfoxstudio** [comment]
> Could you retest from top of main branch or nightly builds?

on latest nightly 
![image](https://github.com/nats-io/nats-server/assets/11800002/a6b502fc-0743-4808-b4b5-1cf4fd99f80a)
![image](https://github.com/nats-io/nats-server/assets/11800002/5cffa92e-cf01-49d6-8365-7395af0c6513)
- sequence problem not fixed.
- consumer problem (stop read new messages).

**Comment by derekcollison** [comment]
What sync interval is the system configured with?

Woukld you be open to a video call?

**Comment by grrrvahrrr** [comment]
> What sync interval is the system configured with?
> 
> Woukld you be open to a video call?

Hi! Sorry for the delayed answer. If it is possible, let's organize a call next week. We continue testing using the latest version and trying to find the roots of this behaviour.

**Comment by derekcollison** [comment]
Looping in @neilalexander and @Jarema and @wallyqs who can coordinate.

**Comment by Jarema** [comment]
Hey @grrrvahrrr! 
Please ping me on NATS slack (@Tomasz Pietrek) or via email (tomasz@synadia.com) so we can schedule something.

**Comment by Marquis42** [comment]
I experienced this same issue last night after a node pool upgrade, I'd be quite Interested in a resolution here.  Was anything gleaned from the aforementioned video call (assuming it's happened)?

**Comment by derekcollison** [comment]
@Marquis42 what server version were you using to do the node pool uphrade?

**Comment by Marquis42** [comment]
We're running 2.10.14 at the moment.

**Comment by derekcollison** [comment]
I believe it was fixed in 2.10.16.

We also are staging 2.10.17 as RC1 now if you want to test..

**Comment by derekcollison** [comment]
https://github.com/nats-io/nats-server/pull/5454

**Comment by Marquis42** [comment]
That's great news, thank you!  I'm not sure if I can reproduce as it's only
happened the one time, but I'll be sure to upgrade at the earliest possible
time.

**Comment by bfoxstudio** [comment]
not fixed in 2.10.17 and 2.10.18



> #5454 
![image](https://github.com/user-attachments/assets/d23dbb99-eddd-4ecc-ae69-471ef5f0a2e2)

**Comment by derekcollison** [comment]
@bfoxstudio Do you have clear instructions we could use to recreate what you are seeing on our side?

**Comment by grrrvahrrr** [comment]
> @bfoxstudio Do you have clear instructions we could use to recreate what you are seeing on our side?

What we are doing is simple - tested for both docker and k3s:
1. we are sending a stream of data into KV
2. check who is the metaleader at the moment and leave this be
3. choose any other node but the metaleader for the test
4. we drain the chosen node in docker or deactivate the pod in k3s
5. wait for the difference in sequences between the offline node and online ones to be around 500
6. we turn the offline node back on and the difference in sequences remain as seen on the last graph

**Comment by derekcollison** [comment]
How big is each message?
How many different keys / subjects?
Does the KV have history?
Could you share stream info for this KV?
What do you mean by drain the node?
What does stream info report for the KV when the offline node is brought back online? (After say 2 mins)

**Comment by grrrvahrrr** [comment]
How big is each message? 0,33 kb

How many different keys / subjects? 22.5k

Does the KV have history? no

What do you mean by drain the node? we switch node availability to Drain in Portainer to simulate server shutdown. here is more info https://docs.docker.com/engine/swarm/swarm-tutorial/drain-node/

stream info and kv info for the stream with desync 

```
Information for Stream KV_wh-px-egeo-e-shard1-kv created 2024-06-28 15:08:29

              Subjects: $KV.wh-px-egeo-e-shard1-kv.>
              Replicas: 5
               Storage: File

Options:

             Retention: Limits
       Acknowledgments: true
        Discard Policy: New
      Duplicate Window: 2m0s
     Allows Msg Delete: false
          Allows Purge: true
        Allows Rollups: true

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: 1
         Maximum Bytes: unlimited
           Maximum Age: unlimited
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

Cluster Information:

                  Name: js_egeo_kv_shard1_infile
                Leader: js_egeo_kv_shard1_infile_node05
               Replica: js_egeo_kv_shard1_infile_node01, current, seen 1.54s ago
               Replica: js_egeo_kv_shard1_infile_node02, current, seen 1.54s ago
               Replica: js_egeo_kv_shard1_infile_node03, current, seen 1.54s ago
               Replica: js_egeo_kv_shard1_infile_node04, current, seen 1.54s ago

State:

              Messages: 22,521
                 Bytes: 7.6 MiB
        First Sequence: 565 @ 2024-06-28 15:09:20 UTC
         Last Sequence: 3,326,244 @ 2024-08-12 11:42:22 UTC
      Deleted Messages: 3,303,159
      Active Consumers: 0
    Number of Subjects: 22,521
```
  
```
    Information for Key-Value Store Bucket wh-px-egeo-e-shard1-kv created 2024-06-28T15:08:29Z

Configuration:

          Bucket Name: wh-px-egeo-e-shard1-kv
         History Kept: 1
        Values Stored: 22,521
   Backing Store Kind: JetStream
          Bucket Size: 7.6 MiB
  Maximum Bucket Size: unlimited
   Maximum Value Size: unlimited
          Maximum Age: unlimited
     JetStream Stream: KV_wh-px-egeo-e-shard1-kv
              Storage: File

Cluster Information:

                 Name: js_egeo_kv_shard1_infile
               Leader: js_egeo_kv_shard1_infile_node05
              Replica: js_egeo_kv_shard1_infile_node01, current, seen 713ms ago
              Replica: js_egeo_kv_shard1_infile_node02, current, seen 712ms ago
              Replica: js_egeo_kv_shard1_infile_node03, current, seen 713ms ago
              Replica: js_egeo_kv_shard1_infile_node04, current, seen 713ms ago
```

**Comment by derekcollison** [comment]
@wallyqs could you look into this a bit and see what we can find?

**Comment by grrrvahrrr** [comment]
@wallyqs  Hi! any news on the issue?

**Comment by katrinwab** [comment]
we tried 
https://hub.docker.com/layers/synadia/nats-server/nightly-20240819/images/sha256-8d9cb4a80c5db196b60b69fea68d56651a0e33be8394b51b7fc832d8030fe7c7

<img width="1467" alt="Снимок экрана 2024-08-19 в 14 10 20" src="https://github.com/user-attachments/assets/71cb947b-d611-4651-b066-96dc82c95a14">

**Comment by wallyqs** [comment]
Thanks for the information about this issue, we have a test reproduction for it and are currently investigating how to address.

**Comment by katrinwab** [comment]
It works for us too, but we would like more stability))

**Comment by bfoxstudio** [comment]
> We solved it for now following the steps here: [#5205 (comment)](https://github.com/nats-io/nats-server/issues/5205#issuecomment-2004181431)
If 1 server cannot handle the load - reducing the number of replicas can lead to complete data loss . Is not a solution but it helps fix the cluster's functionality.

**Comment by derekcollison** [comment]
@katrinwab we have some additional protections going into 2.10.21 release that are landing on main but these are for restoring streams on server start or stream restore.

Is this after restart or just during normal operations?

**Comment by katrinwab** [comment]
we had problems with the network between nodes (
ok, I will try  2.10.21

**Comment by katrinwab** [comment]
@derekcollison yesterday I updated to 2.10.21. but today I got the problem again

**Comment by derekcollison** [comment]
@katrinwab would need quite a bit more information.

Are you a Synadia customer? Is this production impacting?

**Comment by a-alinichenko** [comment]
We have the same problem.
The NATS version is 2.10.21.
When we restart NATS cluster we have the next logs and the pod doesn't work:

`[7] 2024/10/03 10:36:57.943668 [WRN] RAFT [9R4RvVMj - _meta_] Falling behind in health check, commit 59078 != applied 58988
[7] 2024/10/03 10:36:57.943701 [WRN] Healthcheck failed: "JetStream is not current with the meta leader"
[7] 2024/10/03 10:37:07.943402 [WRN] RAFT [9R4RvVMj - _meta_] Falling behind in health check, commit 59108 != applied 58988
[7] 2024/10/03 10:37:07.943423 [WRN] Healthcheck failed: "JetStream is not current with the meta leader"
[7] 2024/10/03 10:37:17.943138 [WRN] RAFT [9R4RvVMj - _meta_] Falling behind in health check, commit 59108 != applied 58988
[7] 2024/10/03 10:37:17.943163 [WRN] Healthcheck failed: "JetStream is not current with the meta leader"
[7] 2024/10/03 10:37:27.943352 [WRN] RAFT [9R4RvVMj - _meta_] Falling behind in health check, commit 59188 != applied 58988
[7] 2024/10/03 10:37:27.943400 [WRN] Healthcheck failed: "JetStream is not current with the meta leader"
[7] 2024/10/03 10:37:37.942694 [WRN] RAFT [9R4RvVMj - _meta_] Falling behind in health check, commit 59298 != applied 58988
[7] 2024/10/03 10:37:37.942806 [WRN] Healthcheck failed: "JetStream is not current with the meta leader"
[7] 2024/10/03 10:37:47.943473 [WRN] RAFT [9R4RvVMj - _meta_] Falling behind in health check, commit 59308 != applied 58988
[7] 2024/10/03 10:37:47.943498 [WRN] Healthcheck failed: "JetStream is not current with the meta leader"
[7] 2024/10/03 10:37:57.943104 [WRN] RAFT [9R4RvVMj - _meta_] Falling behind in health check, commit 59388 != applied 58988
[7] 2024/10/03 10:37:57.943135 [WRN] Healthcheck failed: "JetStream is not current with the meta leader"`


Here is the stream info:

`Information for Stream ch_queue6 created 2024-09-18 18:54:04

              Subjects: requests6, antibot6
              Replicas: 1
               Storage: File
     Placement Cluster: nats-sessions-api
        Placement Tags: pod:nats-sessions-api-6

Options:

             Retention: WorkQueue
       Acknowledgments: true
        Discard Policy: Old
      Duplicate Window: 10m0s
     Allows Msg Delete: true
          Allows Purge: true
        Allows Rollups: false

Limits:

      Maximum Messages: 100,000,000,000
   Maximum Per Subject: unlimited
         Maximum Bytes: unlimited
           Maximum Age: 7d0h0m0s
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

Cluster Information:

                  Name: nats-sessions-api
                Leader: nats-sessions-api-6

State:

              Messages: 961,995
                 Bytes: 1.1 GiB
        First Sequence: 3,884,371,968 @ 2024-10-03 13:11:18 UTC
         Last Sequence: 3,885,335,265 @ 2024-10-03 13:21:41 UTC
      Deleted Messages: 1,303
      Active Consumers: 2
    Number of Subjects: 2`
